### ISSUE TITLE
yt_dlp: build of new version 2024.10.22 fails

### ISSUE THREAD

**Issue by humdingerb** [haikuports/haikuports#11254]
This needs someone familiar with Python, I suppose...

Using the existing recipe, just renamed to the new version results in this build error:

```
* Building wheel...
Traceback (most recent call last):
  File "/packages/python3.10-3.10.14-5/.self/lib/python3.10/vendor-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in <module>
    main()
  File "/packages/python3.10-3.10.14-5/.self/lib/python3.10/vendor-packages/pyproject_hooks/_in_process/_in_process.py", line 357, in main
    json_out["return_val"] = hook(**hook_input["kwargs"])
  File "/packages/python3.10-3.10.14-5/.self/lib/python3.10/vendor-packages/pyproject_hooks/_in_process/_in_process.py", line 271, in build_wheel
    return _build_backend().build_wheel(
  File "/packages/python3.10-3.10.14-5/.self/lib/python3.10/vendor-packages/hatchling/build.py", line 56, in build_wheel
    return os.path.basename(next(builder.build(wheel_directory, ['standard'])))
  File "/packages/python3.10-3.10.14-5/.self/lib/python3.10/vendor-packages/hatchling/builders/plugin/interface.py", line 93, in build
    self.metadata.validate_fields()
  File "/packages/python3.10-3.10.14-5/.self/lib/python3.10/vendor-packages/hatchling/metadata/core.py", line 244, in validate_fields
    self.core.validate_fields()
  File "/packages/python3.10-3.10.14-5/.self/lib/python3.10/vendor-packages/hatchling/metadata/core.py", line 1325, in validate_fields
    getattr(self, attribute)
  File "/packages/python3.10-3.10.14-5/.self/lib/python3.10/vendor-packages/hatchling/metadata/core.py", line 978, in classifiers
    raise ValueError(message)
ValueError: Unknown classifier in field `project.classifiers`: Programming Language :: Python :: 3.13

ERROR Backend subprocess exited when trying to invoke build_wheel
```

The [Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.10.22) mention some important changes. Related? :

> Following this release, yt-dlp's Python dependencies must be installed using the default group
If you're installing yt-dlp with pip/pipx or requiring yt-dlp in your own Python project, you'll need to specify yt-dlp[default] if you want to also install yt-dlp's optional dependencies (which were previously included by default). https://github.com/yt-dlp/yt-dlp/pull/11255

**Comment by korli** [comment]
You need to bump the version of [dev-python](https://github.com/haikuports/haikuports/tree/master/dev-python)/[hatchling](https://github.com/haikuports/haikuports/tree/master/dev-python/hatchling)

**Comment by Begasus** [comment]
Does this mean the websocket package is also needed now?

**Comment by korli** [comment]
> Does this mean the websocket package is also needed now?

Hmm dunno. Doesn't look like, seeing the error in hatchling.

**Comment by Begasus** [comment]
I've had some talks about this on IRC with @humdingerb  and @OscarL , so far it doesn't seem a "hard" requirement (or hasn't popped up as such), but I've seen it being used correctly when building running PlasmaTube (or rather seeing the output in Terminal that lead me to see it was missing).
From upstream:
https://github.com/bashonly/yt-dlp/blob/a7749056a7c6e817ae0555d442a95e2e55fe09a0/pyproject.toml#L55

Anyway, if need be I have it lying around here. :)

**Comment by korli** [comment]
bumped hatchling, trove-classifiers, yt-dlp in 716850ea4e39bc67c36656923b5af56089656837
