### ISSUE TITLE
Album build fails on 64 bit

### ISSUE THREAD

**Issue by Vidrep** [haikuports/haikuports#1387]
First error: missing dependency (libiptcdata)

 Fetching package for devel:libiptcdata ...
*** Failed to find a match for "devel:libiptcdata": Name not found
Error: unable to resolve required packages for build for album-0.9.4
Error:  dependency-infos:
Error:          /boot/home/haikuports/repository/album-0.9.4.DependencyInfo
Error:  repositories:
Error:          [u'/boot/home/haikuports/packages', '/boot/system/packages']
Error: 

Build and install libiptcdata and continue build process for Album

Second error:

collect2: error: ld returned 1 exit status
/boot/system/develop/etc/makefile-engine:246: recipe for target 'objects/Album' failed
make: *** [objects/Album] Error 1
Traceback (most recent call last):
  File "/boot/home/haikuporter/HaikuPorter/Port.py", line 1222, in _executeInChroot
  File "/boot/home/haikuporter/HaikuPorter/Port.py", line 773, in taskFunction
  File "/boot/home/haikuporter/HaikuPorter/Port.py", line 1298, in _executeBuild
  File "/boot/home/haikuporter/HaikuPorter/Port.py", line 1383, in _doBuildStage
  File "/boot/home/haikuporter/HaikuPorter/Port.py", line 1492, in _doRecipeAction
  File "/boot/home/haikuporter/HaikuPorter/Port.py", line 1527, in _openShell
  File "/packages/python-2.7.13-1/.self/lib/python2.7/subprocess.py", line 186, in check_call
CalledProcessError: Command '['bash', '-c', '. /wrapper-script']' returned non-zero exit status 2
Traceback (most recent call last):
  File "/boot/home/haikuporter/HaikuPorter/Main.py", line 39, in __init__
    self.run(args)
  File "/boot/home/haikuporter/HaikuPorter/Main.py", line 402, in run
    self._buildPort(port, True, self.packagesPath)
  File "/boot/home/haikuporter/HaikuPorter/Main.py", line 625, in _buildPort
    port.build(self.packagesPath, self.options.package, targetPath)
  File "/boot/home/haikuporter/HaikuPorter/Port.py", line 789, in build
    self._executeInChroot(chrootSetup, makeChrootFunctions())
  File "/boot/home/haikuporter/HaikuPorter/Port.py", line 1238, in _executeInChroot
    chrootFunctions['failure']()
  File "/boot/home/haikuporter/HaikuPorter/Port.py", line 780, in failureFunction
    sysExit(u'Build has failed - stopping.')
  File "/boot/home/haikuporter/HaikuPorter/Utils.py", line 66, in sysExit
    sys.exit(message.encode('utf-8'))
SystemExit: Error: Build has failed - stopping.

**Comment by Vidrep** [comment]
Reposted on HaikuArchives
