### ISSUE TITLE
python3_x86 doesn't include the zlib module

### ISSUE THREAD

**Issue by korli** [haikuports/haikuports#2084]
from http://vmpkg.haiku-os.org/master/x86_gcc2/buildruns/679/builds/26892.log

````
creating 'dist/asciinema-1.4.0-py3.6.egg' and adding 'build/bdist.haiku-1-BePC/egg' to it
Traceback (most recent call last):
  File "setup.py", line 42, in <module>
    'Topic :: Utilities'
  File "/packages/python3_asciinema-1.4.0-1/cmd~python3/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/packages/python3_asciinema-1.4.0-1/cmd~python3/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/packages/python3_asciinema-1.4.0-1/cmd~python3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/packages/python3_asciinema-1.4.0-1/cmd~python3/lib/python3.6/vendor-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/packages/python3_asciinema-1.4.0-1/cmd~python3/lib/python3.6/vendor-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/packages/python3_asciinema-1.4.0-1/cmd~python3/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/packages/python3_asciinema-1.4.0-1/cmd~python3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/packages/python3_asciinema-1.4.0-1/cmd~python3/lib/python3.6/vendor-packages/setuptools/command/bdist_egg.py", line 223, in run
    dry_run=self.dry_run, mode=self.gen_header())
  File "/packages/python3_asciinema-1.4.0-1/cmd~python3/lib/python3.6/vendor-packages/setuptools/command/bdist_egg.py", line 465, in make_zipfile
    z = zipfile.ZipFile(zip_filename, mode, compression=compression)
  File "/packages/python3_asciinema-1.4.0-1/cmd~python3/lib/python3.6/zipfile.py", line 1066, in __init__
    _check_compression(compression)
  File "/packages/python3_asciinema-1.4.0-1/cmd~python3/lib/python3.6/zipfile.py", line 649, in _check_compression
    "Compression requires the (missing) zlib module")
````

**Comment by korli** [comment]
3661344276346ffbeff297c73cd2b3ef6b965777 could explain the problem

**Comment by korli** [comment]
Seems to be resolved somehow.
