### ISSUE TITLE
Write recipe for pgcli

### ISSUE THREAD

**Issue by scottmc** [haikuports/haikuports#3259]
https://github.com/dbcli/pgcli

**Comment by Begasus** [comment]
Requires a few more python packages, had some ready but ended up not being able to build on for psycobg: https://github.com/psycopg/psycopg

Fails with some import:
```
Copying psycopg.egg-info to /packages/psycopg-3.1.9-1/.self/lib/python3.9/vendor-packages/psycopg-3.1.9-py3.9.egg-info
running install_scripts
/packages/psycopg_python39-3.1.9-1/.self
Fatal Python error: init_sys_streams: can't initialize sys standard streams
Python runtime state: core initialized
Traceback (most recent call last):
  File "/packages/python3.10-3.10.12-1/.self/lib/python3.10/io.py", line 52, in <module>
  File "/sources/psycopg-3.1.9/psycopg/psycopg/abc.py", line 7, in <module>
  File "/packages/python3.10-3.10.12-1/.self/lib/python3.10/typing.py", line 22, in <module>
ImportError: cannot import name 'abstractmethod' from partially initialized module 'abc' (most likely due to a circular import) (/sources/psycopg-3.1.9/psycopg/psycopg/abc.py)
```
