### ISSUE TITLE
meson broken?

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#3800]
After trying to build something with meson (libmpdclient, libepoxy) I'm getting the next errors:
From haikuporter:
```
Traceback (most recent call last):
    File "/bin/meson", line 6, in <module>
      from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
```
From Terminal:
```
[x86] ~/WIP/libepoxy-1.5.3/build> meson --buildtype=release --prefix=/boot/home/destdir/
  Traceback (most recent call last):
    File "/bin/meson", line 6, in <module>
      from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by Begasus** [comment]
Seems like this is linked to the new python version (3.7), setuptools should be rebuild against the new version for pymhon, then the latest meson can be build against the correct version of setuptools (which requires 3.6 atm)
