### ISSUE TITLE
pyopengl: failed to import OpenGL.GL

### ISSUE THREAD

**Issue by iam-git** [haikuports/haikuports#5368]
I am pleasantly surprised to find pyopengl in HaikuDepot, but I was unable to start playing with it. 
`>>> import OpenGL.GL
===== 2020.10.29 23:10:12 =====
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/packages/python3-3.7.9-1/.self/lib/python3.7/vendor-packages/OpenGL/GL/__init__.py", line 4, in <module>
    from OpenGL.GL.VERSION.GL_1_1 import *
  File "/packages/python3-3.7.9-1/.self/lib/python3.7/vendor-packages/OpenGL/GL/VERSION/GL_1_1.py", line 14, in <module>
    from OpenGL.raw.GL.VERSION.GL_1_1 import *
  File "/packages/python3-3.7.9-1/.self/lib/python3.7/vendor-packages/OpenGL/raw/GL/VERSION/GL_1_1.py", line 7, in <module>
    from OpenGL.raw.GL import _errors
  File "/packages/python3-3.7.9-1/.self/lib/python3.7/vendor-packages/OpenGL/raw/GL/_errors.py", line 4, in <module>
    _error_checker = _ErrorChecker( _p, _p.GL.glGetError )
  File "/packages/python3-3.7.9-1/.self/lib/python3.7/vendor-packages/OpenGL/error.py", line 183, in __init__
    self._isValid = platform.CurrentContextIsValid
  File "/packages/python3-3.7.9-1/.self/lib/python3.7/vendor-packages/OpenGL/platform/baseplatform.py", line 15, in __get__
    value = self.fget( obj )
  File "/packages/python3-3.7.9-1/.self/lib/python3.7/vendor-packages/OpenGL/platform/baseplatform.py", line 356, in CurrentContextIsValid
    return self.GetCurrentContext
  File "/packages/python3-3.7.9-1/.self/lib/python3.7/vendor-packages/OpenGL/platform/baseplatform.py", line 15, in __get__
    value = self.fget( obj )
  File "/packages/python3-3.7.9-1/.self/lib/python3.7/vendor-packages/OpenGL/platform/glx.py", line 95, in GetCurrentContext
    return self.GL.glXGetCurrentContext
  File "/packages/python3-3.7.9-1/.self/lib/python3.7/ctypes/__init__.py", line 377, in __getattr__
    func = self.__getitem__(name)
  File "/packages/python3-3.7.9-1/.self/lib/python3.7/ctypes/__init__.py", line 382, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: No such file or directory
`

Should it work?

**Comment by extrowerk** [comment]
glXGetCurrentContext sespicious to me.
