### ISSUE TITLE
qutebrowser: 2.4.0-1 build fails on hrev56637 x64

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#7554]
Build fails:
```
waiting for build package qutebrowser-2.4.0-1 to be activated
Building ...
a2x -f manpage doc/qutebrowser.1.asciidoc
Traceback (most recent call last):
  File "/bin/a2x", line 10, in <module>
    from importlib.metadata import distribution
ModuleNotFoundError: No module named 'importlib.metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bin/a2x", line 13, in <module>
    from importlib_metadata import distribution
ModuleNotFoundError: No module named 'importlib_metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bin/a2x", line 15, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
misc/Makefile:17: recipe for target 'doc/qutebrowser.1' failed
make: *** [doc/qutebrowser.1] Error 1
Warning: Command '['bash', '-c', '. /wrapper-script']' returned non-zero exit status 2.
Error: Build has failed - stopping.

```

**Comment by kenmays** [comment]
Fixed. We need to provide updated pyqt5 for python >3.8.
