### ISSUE TITLE
Nodejs14 and Nodejs16 "Bug"

### ISSUE THREAD

**Issue by Glog78** [haikuports/haikuports#8533]
while testing different things i stumbled across this "bug"

bash-language-server --version
/boot/home/config/non-packaged/data/yarn/global/node_modules/zod/lib/types.js:325
const emojiRegex = /^(\p{Extended_Pictographic}|\p{Emoji_Component})+$/u;
                   ^

SyntaxError: Invalid regular expression: /^(\p{Extended_Pictographic}|\p{Emoji_Component})+$/: Invalid property name
    at Object.<anonymous> (/boot/home/config/non-packaged/data/yarn/global/node_modules/zod/lib/types.js:325:20)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/boot/home/config/non-packaged/data/yarn/global/node_modules/zod/lib/external.js:17:14)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)

**Comment by korli** [comment]
Isn't it like https://github.com/colinhacks/zod/issues/2302 or https://github.com/colinhacks/zod/issues/2269 ?

**Comment by korli** [comment]
Thanks, closing
